# https://github.com/argoproj/argo-rollouts/blob/3f5960efc21b5d8db44cbf20b779ab74d6fdaa99/utils/istio/istio.go#L40
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: frontend
  namespace: tsmc-nycu-lab-13
  # namespace: istio-system
spec:
  host: frontend.tsmc-nycu-lab-13.svc.cluster.local
  subsets:
  - name: canary
    labels:
      app: frontend
  - name: stable
    labels:
      app: frontend
